name: firebase
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  fl_chart: ^0.68.0
  animate_do: ^3.3.4
  riverpod: ^2.6.0
  firebase_auth: ^5.3.1
  provider: ^6.1.2
  flutter_riverpod: ^2.6.0
  uuid: ^4.5.1
  flutter_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/Gasera-full-color.png  
  - assets/Gasera-white.png
  - assets/

