// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEbMpPOjOX4mSwCQa2eFa0UjVKUOunvJU',
    appId: '1:1041306767120:web:0a905163ac095b00e71f95',
    messagingSenderId: '1041306767120',
    projectId: 'gasera-flutter-react',
    authDomain: 'gasera-flutter-react.firebaseapp.com',
    storageBucket: 'gasera-flutter-react.appspot.com',
    measurementId: 'G-TMVE9FF7MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWuORrOPnJElBhh-9xV9Le-IDArr9ooQ4',
    appId: '1:1041306767120:android:903ccd7efdc35a50e71f95',
    messagingSenderId: '1041306767120',
    projectId: 'gasera-flutter-react',
    storageBucket: 'gasera-flutter-react.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRkGuO21oqDsl7qyh_Bs593pvLf7d2eME',
    appId: '1:1041306767120:ios:da3f5675972a1cc9e71f95',
    messagingSenderId: '1041306767120',
    projectId: 'gasera-flutter-react',
    storageBucket: 'gasera-flutter-react.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRkGuO21oqDsl7qyh_Bs593pvLf7d2eME',
    appId: '1:1041306767120:ios:da3f5675972a1cc9e71f95',
    messagingSenderId: '1041306767120',
    projectId: 'gasera-flutter-react',
    storageBucket: 'gasera-flutter-react.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEbMpPOjOX4mSwCQa2eFa0UjVKUOunvJU',
    appId: '1:1041306767120:web:65c45f4cd3c56703e71f95',
    messagingSenderId: '1041306767120',
    projectId: 'gasera-flutter-react',
    authDomain: 'gasera-flutter-react.firebaseapp.com',
    storageBucket: 'gasera-flutter-react.appspot.com',
    measurementId: 'G-4JSXFGWN89',
  );

}